### ISSUE TITLE
disk-io3: Fails on Proxmox VE

### ISSUE THREAD

**Issue by berrnd** [Linuxfabrik/monitoring-plugins#552]
**Describe the bug**
On Proxmox VE, `disk-io3` fails with that error:
```
bb@ct-mon1:/opt/centralcfg/scripts/icinga/linuxfabrik-monitoring-plugins$ ./disk-io3
Traceback (most recent call last):
  File "/opt/centralcfg/scripts/icinga/linuxfabrik-monitoring-plugins/./disk-io3", line 294, in 'module'
    main()
  File "/opt/centralcfg/scripts/icinga/linuxfabrik-monitoring-plugins/./disk-io3", line 131, in main
    lib.base3.version(platform.release()) '= lib.base3.version('4.18.0'),
  File "/opt/centralcfg/scripts/icinga/linuxfabrik-monitoring-plugins/lib/base3.py", line 617, in version
    return tuple(map(int, (v.split("."))))
ValueError: invalid literal for int() with base 10: ''
```

**Environment:**
 - `uname -a`: 
```
Linux ct-mon1 5.13.19-4-pve #1 SMP PVE 5.13.19-9 (Mon, 07 Feb 2022 11:01:14 +0100) x86_64 GNU/Linux
```

This is due to that `platform.release()` contains more than 1 hyphen which leads a comparision based on `lib.base3.version()` to fail.

I will provide a fix / pull request to fix that shortly at [Linuxfabrik/lib](https://github.com/Linuxfabrik/lib).

**Comment by markuslf** [comment]
Fix implemented in base3.py: https://github.com/Linuxfabrik/lib/commit/3eac3b87f2fd50add822a1ba9fa5e7e380a194cb
