### ISSUE TITLE
infomaniak-swiss-backup-devices3: TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/monitoring-plugins#582]
**Describe the bug**
Happened once:
```
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/infomaniak-swiss-backup-devices", line 213, in 'module'
    main()
  File "/usr/lib64/nagios/plugins/infomaniak-swiss-backup-devices", line 182, in main
    lib.human3.seconds2human(lib.time3.now(as_type='epoch') - slot_data.get('usage_last_check')),
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by markuslf** [comment]
Already fixed.
