### ISSUE TITLE
disk-smart3: Getting error:  "KeyError: 'serial_number'"

### ISSUE THREAD

**Issue by benjofalanga** [Linuxfabrik/monitoring-plugins#659]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] Compiled, from repo
- [X] Source Code, from GitHub

## Issue with disk-smart plugin

---

Hello 
I am using the disk-smart plugin from my Icinga infrastructure and it works on most of my hosts , however I'm getting the following issue on some of them.
I run the plugin with this command:

```
'/usr/bin/sudo' '/usr/lib/nagios/plugins/disk-smart3' '--ignore' '[]'
```
 the following output error message is show:
```
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/disk-smart3", line 910, in 'module'
    main()
  File "/usr/lib/nagios/plugins/disk-smart3", line 868, in main
    serial_number = disk_report['general']['serial_number']
KeyError: 'serial_number'
```
---

### Steps to reproduce - Plugin call

'/usr/bin/sudo' '/usr/lib/nagios/plugins/disk-smart3' '--ignore' '[]'

### Environment

```
Linux argentina 4.15.0-167-generic #175-Ubuntu SMP Wed Jan 5 01:56:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
### Output from lsblk
```
NAME                   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                      8:0    0  7.3T  0 disk 
├─sda1                   8:1    0    1M  0 part 
├─sda2                   8:2    0  488M  0 part /boot
└─sda3                   8:3    0  7.3T  0 part 
  ├─belarus--vg-root   253:0    0  7.2T  0 lvm  /
  └─belarus--vg-swap_1 253:1    0   48G  0 lvm  [SWAP]
sr0                     11:0    1 1024M  0 rom  
```
### Plugin Version

disk-smart3: v2023021701 by Linuxfabrik GmbH, Zurich/Switzerland 

### Python version

Python 3.6.9

**Comment by markuslf** [comment]
I need some test data. Please run `sudo lsblk --nodeps --output name,type --noheadings --exclude 9,11,230,252,253,254` to get a list of disks. Then, for each disk except loop run `smartctl --xall /dev/your-disk`, and paste the complete output of this command.

**Comment by benjofalanga** [comment]
Hey 
```
sudo lsblk --nodeps --output name,type --noheadings --exclude 9,11,230,252,253,254

sda  disk
```

```
sudo smartctl --xall /dev/sda

smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-151-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               DELL
Product:              PERC H710
Revision:             3.13
User Capacity:        7,999,376,588,800 bytes [7.99 TB]
Logical block size:   512 bytes
Logical Unit id:      0x6c81f660d4d3c900207912560b4e3fea
Serial number:        00ea3f4e0b5612792000c9d3d460f681
Device type:          disk
Local Time is:        Thu Mar 30 09:23:36 2023 UTC
SMART support is:     Unavailable - device lacks SMART capability.
Read Cache is:        Disabled
Writeback Cache is:   Disabled

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging
Device does not support Background scan results logging
```
```
sudo smartctl --xall /dev/disk
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-151-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/disk: Unable to detect device type
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```


> I need some test data. Please run `sudo lsblk --nodeps --output name,type --noheadings --exclude 9,11,230,252,253,254` to get a list of disks. Then, for each disk except loop run `sudo smartctl --xall /dev/your-disk`, and paste the complete output of this command.

**Comment by markuslf** [comment]
Unable to reproduce, the data validates correctly. I get:
```
Checked 1 disk. All are healthy.
* sda (PERC H710, Unknown model, SerNo 00ea3f4e0b5612792000c9d3d460f681)
  - Info: SMART is not supported. You won't be able to read any SMART information from this drive. Consider adding it to the ignore list.
```

Can you do me a favor and replace lines 866 and 867
```
        disk_report = parse_sections(stdout)
        disk_count += 1
```
by
```
        print(stdout)
        disk_report = parse_sections(stdout)
        disk_count += 1
        print(disk_report)
```

then run the check again on the command line of the failing machine and send me the new output? Just `sudo /usr/lib/nagios/plugins/disk-smart3`, without `--ignore '[]'`

**Comment by benjofalanga** [comment]
Sorry I have run the previous checks on the wrong host 
This is the correct output :
```
sudo lsblk --nodeps --output name,type --noheadings --exclude 9,11,230,252,253,254
loop0  loop
loop1  loop
loop2  loop
loop3  loop
loop4  loop
loop5  loop
loop6  loop
loop8  loop
loop9  loop
loop10 loop
sda    disk
```

```
sudo smartctl --xall /dev/sda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-167-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               Dell
Product:              VIRTUAL DISK
Revision:             1028
User Capacity:        7,999,376,588,800 bytes [7.99 TB]
Logical block size:   512 bytes
Logical Unit id:      0x600508e000000000e2704eddeccfd009
Device type:          disk
Local Time is:        Thu Mar 30 10:12:03 2023 UTC
SMART support is:     Unavailable - device lacks SMART capability.
Read Cache is:        Enabled
Writeback Cache is:   Disabled

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging
Device does not support Background scan results logging
```

```
sudo smartctl --xall /dev/loop0
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-167-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/loop0: Unable to detect device type
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```

```
sudo /usr/lib/nagios/plugins/disk-smart3
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-167-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               Dell
Product:              VIRTUAL DISK
Revision:             1028
User Capacity:        7,999,376,588,800 bytes [7.99 TB]
Logical block size:   512 bytes
Logical Unit id:      0x600508e000000000e2704eddeccfd009
Device type:          disk
Local Time is:        Thu Mar 30 10:18:59 2023 UTC
SMART support is:     Unavailable - device lacks SMART capability.
Read Cache is:        Enabled
Writeback Cache is:   Disabled

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging
Device does not support Background scan results logging

{'health': {'w': 'none', 'msg': ''}, 'attributes': {'w': 'none', 'msg': '', 'perfdata': {}}, 'error_log': {'w': 'none', 'msg': ''}, 'statistics': {'w': 'none', 'msg': ''}, 'general': {'model': 'VIRTUAL DISK', 'device_model': 'Unknown model', 'w': 'notice', 'msg': "  - Info: SMART is not supported. You won't be able to read any SMART information from this drive. Consider adding it to the ignore list.\n"}}
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/disk-smart3", line 912, in 'module'
    main()
  File "/usr/lib/nagios/plugins/disk-smart3", line 870, in main
    serial_number = disk_report['general']['serial_number']
KeyError: 'serial_number'
```

**Comment by markuslf** [comment]
That helped a lot, thanks. Fixed.
