### ISSUE TITLE
qts-disk-smart: Plugin not working since new update

### ISSUE THREAD

**Issue by dishorned** [Linuxfabrik/monitoring-plugins#696]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [X] Source Code from GitHub

### Bug description

The plugin worked great until the last Qnap Firmware update to firmware version: QTS 5.1.0.2466

Since then, I get the following error:

`Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/c_check_qts-disk-smart", line 181, in 'module'
    main()
  File "/usr/lib/nagios/plugins/c_check_qts-disk-smart", line 141, in main
    for disk in data["Disk_Info"]["entry"]:
KeyError: 'Disk_Info'`

Does anyone else get this error since the last firmware update, or does this just happen on mine?
I use some other qts-plugins from you guys, and the others still work as expected.

### Steps to reproduce - Plugin call

'/usr/lib/nagios/plugins/qts-disk-smart' '--insecure' '--password' 'somepassword' '--url' 'https://url:4444' '--username' 'someusername'

### Environment

Linux hostname 5.10.0-23-amd64 #1 SMP Debian 5.10.179-2 (2023-07-14) x86_64 GNU/Linux

QNAP 673 with latest firmware.

### Plugin Version

v2023071203

### Python version

3.9.2

**Comment by sandrolf** [comment]
```
QTS 5.1.0.2466 build 20230721

[Important Notes]
- In QTS 5.0.1 or earlier, users can no longer create new VJBOD disks from a remote NAS if the remote NAS is running QTS 5.1.0 or later. If there are existing VJBOD disks connections to the remote NAS before it is updated to QTS 5.1.0 or later, these VJBOD disks are unaffected and remain operational after the update. In QTS 5.1.0 or later, users can still create VJBOD disks from a remote NAS running QTS 5.0.1 or earlier.
- To use QNAP cloud services, please ensure that your network environment can access our service endpoints. For details, see https://www.qnap.com/go/how-to/faq/con_show.php?cid=2851
- Removed support for CO Video.

[New Features]
Control Panel
- Administrators can now delegate roles to non-administrators in Control Panel > Privilege > Delegated Administration. This feature allows non-administrators to perform routine tasks and manage system resources, thus greatly enhancing productivity and flexibility.
- Added support for Hailo-8 AI accelerator devices. Users can also configure Hailo-8 usage priorities for apps using Hailo-8 devices.
- Added the client umask feature to assigns default permissions for existing and new files and folders.
- Added the Qfinder discovery service that allows the Qfinder Pro utility to discover your QNAP device.

Desktop
- You can now log out of your account on all devices, browsers, and applications at once. To use this feature, go to the desktop, click your username on the taskbar, and then go to Login and Security > Password.
- Added an icon on the top-right corner of the desktop to indicate whether the device has enabled myQNAPcloud and been associated with a QNAP ID or whether the device has joined AMIZ Cloud.

File Station
- Enhanced the search function and search result interface. Users can now search file content with Qsirch.
- Added support for the Recent Files function. Users can now quickly browse recently uploaded/accessed/deleted files.

Help Center
- Redesigned the user interface of Help Center for a better user experience.

Initialization
- You can now purchase licenses during QuTScloud installation.

iSCSI & Fibre Channel
- Added support for enabling async IO for block-based LUNs, which can improve the performance of a LUN over an iSCSI connection particularly when the LUN contains dual-actuator HDDs. To find this setting, go to iSCSI & Fibre Channel > iSCSI Storage, select a block-based LUN, and click Action > Modify.
- Added a new settings page for managing default iSCSI CHAP authentication settings, which you can use for multiple iSCSI targets. You can find these settings in iSCSI & Fibre Channel > Global Settings > Default iSCSI CHAP. When creating or editing a target, you can choose to use the default CHAP settings or configure unique settings for the target.

myQNAPcloud
- You can now add the NAS to an organization when setting up myQNAPcloud. This allows organization administrators to centrally manage and monitor various system resources on NAS devices via AMIZ Cloud. (AMIZ Cloud Agent must be enabled in myQNAPcloud.)

Network & Virtual Switch
- Network & Virtual Switch can now record event logs when the system identifies conflicting IP addresses between the local device and another device on the same network.
- When selecting the system default gateway automatically, you can now configure the checking target by specifying the domain name or IP address.
- Users can now configure the MAC address when creating or modifying a virtual switch.

NFS
- Users can now set the rcpbind to assign fixed ports to RPC services. Make sure that you configure the firewall rules accordingly to allow connections only on the fixed ports.

SAMBA
- Microsoft networking now supports SMB multichannel settings, which allows file servers to use multiple network connections simultaneously.

Storage&Snapshots
- Added a new window that automatically appears when you insert new disks and helps you decide what to do with them. You can also access this window any time by going to Storage & Snapshots > Storage > Disks/VJBOD > Disks > More > Manage Free Disks.
- Added support for enabling Native Command Queuing (NCQ), which improves the read and write performance of SATA disks.
- Added support for disk failure prediction from ULINK's DA Drive Analyzer. Registered users of DA Drive Analyzer can now also monitor disk failure prediction statuses in Storage & Snapshots > Storage > Disks/VJBOD > Disks.
- Added support for Western Digital Device Analytics (WDDA) for Western Digital (WD) disks. To view WDDA information, go to Storage & Snapshots > Storage > Disks/VJBOD > Disks, select a WD disk, and click Health > View Details.

System
- QTS now supports Passwordless Login, which replaces your password with a more secure verification method. QTS now also supports more verification methods for 2-Step Verification. To configure these settings, go to the desktop, click your username on the taskbar, and then select Login and Security.
- You can now scan the QR code of your NAS with a QNAP mobile app to easily add this NAS to your mobile app. This QR code contains essential network information for remote connection. To get this QR code, go to Desktop > More > Device QR Code.

[Enhancement]
App Center
- Users can now configure a schedule for automatic installations of app updates.

Control Panel
- You can now specify a custom unique identifier (UID) for a new user and edit the UID of an existing user. Note: Arbitrarily changing UIDs may cause access issues for a user.
- The time interval for observing successive failed login attempts can now be configured to be between 0 and 600 minutes. Moreover, a time interval of 0 minutes means that failed login attempts are never reset.
- Changed the behavior and the description of certain permission settings as we do not recommend using the default administrator account "admin".
- You can now include more information from account profiles when importing and exporting user accounts.
- Added additional specification information for memory slots in Control Panel > System Status > Hardware Information.
- You can now select the direction to append the custom header for the reverse proxy rule.
- Optimized the process of restoring the LDAP database.
- The automatic firmware update settings have been streamlined with the following changes:
*The selectable options for automatic firmware updates have been greatly simplified. Users now select one of three firmware types to automatically update their system with: quality updates, critical updates, or latest updates.
*"Security updates" are now "critical updates". Critical updates include security fixes as well as critical system issue fixes.
*"Quality updates" now include security fixes and critical issue fixes in addition to bug fixes.
*"Feature updates" are now "latest updates" and include quality and critical updates in addition to new features, enhancements, and bug fixes.
* Update notifications no longer need to be enabled separately for each firmware type. Notifications are now either enabled or disabled for all firmware types.
- You can now edit, enable, and disable power schedules.

File Station
- Added prompt banners to remind users to turn on related browsing functions for multimedia files.
- Improved File Station performance and enhanced file browsing experience.
- Enhanced the Background Tasks display UI.

iSCSI & Fibre Channel
- When creating an iSCSI target, you can now select the network interfaces that an iSCSI target will use for data transmission. Previously, users could only do so after the target was created.

Login
- Users can now save their QTS login credentials in their web browser. To enhance the security of your QTS user account, we recommend enabling 2-step verification.

NFS
- NFS service now supports both NFSv4 and NFSv4.1 protocols.

PHP System Module
- Updated the built-in PHP version to 8.2.0.

Resource Monitor
- Resource Monitor now displays the space used by files created from Qsync file versioning.

SAMBA
- The SMB protocol now supports the AES GMAC 128-bit key encryption.
- You can now aggregate up to 50 shared folders on a Windows network.
- Updated Samba to version 4.15.
- The kernel-mode SMB daemon is now enabled by default.

Storage&Snapshots
- Expanded and improved the "Activate Predictive S.M.A.R.T. Migration" feature and renamed it "Predictive Migration". Previously, this feature automatically migrated data from a faulty disk to a spare disk when S.M.A.R.T. errors were detected on the faulty disk. Now, users can specify various trigger events from sources other than S.M.A.R.T., including Western Digital Device Analytics, IronWolf Health Management, DA Drive Analyzer, and SSD estimated life remaining. You can configure this feature in Storage & Snapshots > Global Settings > Disk / Device.
- When adding a remote disk, more information is now provided on each LUN in the LUN list to help users identify which one to select.
- After rebuilding a RAID group with a spare disk, the failed disk's slot becomes reserved for a spare disk. To free up this slot for other purposes, go to Storage & Snapshots > Storage > Disks/VJBOD > Disks, select the disk slot, and click Action > Free Up Spare Disk Slot.
- You can now select and configure multiple spare disks when creating a storage pool.
- Redesigned the presentation of disk information into tabular format for enhanced user experience, now viewable in Storage & Snapshots > Storage > Disks/VJBOD > Disks.
- Users can now see disk error logs in QuLog Center.
- Redesigned the presentation of NAS and enclosure information into tabular format for enhanced user experience, now viewable in Storage & Snapshots > Storage > Disks/VJBOD > NAS & Enclosure.
- Qtier now supports more flexible tier configurations with NVMe and SATA SSDs.
- In Storage & Snapshots > Storage > Disks/VJBOD > Disks, information on each disk's slot number, form factor, interface, and disk type are now presented together and enhanced with colored tags so that users can more easily identify each unique disk and disk slot.
- Updated the UI design of various snapshot-related screens to improve user experience in finding relevant information and functions.
- Added support for 2-step verification when connecting to a remote NAS in the Create Virtual JBOD Disk Wizard.
- Renamed the function "Replace & Detach" to "Replace" and added the option for users to choose whether to designate the replaced disk as a spare disk or to detach it from the system.
- After creating a SED secure static volume or SED secure storage pool, the encryption key file is now automatically downloaded to help users unlock the volume or pool in case they forget the encryption password.
- Improved SED-related UI strings for clarity.
- Users can now change the destination of an existing Snapshot Replica job.
- Enhanced the UI for snapshot deletion to provide more information for snapshot statuses and background tasks.
- Added the new IronWolf Health Management (IHM) status "Critical Warning" for Seagate drives. The new IHM status replaces "Not Available" as a trigger event in Predictive Migration. QTS also no longer blocks a Seagate drive when the drive's warranty status cannot be obtained from Seagate servers.

System
- You now need to enter a verification code when resetting your password if you forgot your password. This extra step helps enhance your account security.

[Fixed Issues]
- Resolved an issue where after upgrading their NAS to QTS 5.1.0, users could not map a LUN originally created in earlier versions of QTS released in or before 2019.
- Fixed an issue where users could not join a Windows device to the NAS domain controller after updating Windows 10 to KB5028166.
- Fixed an issue in QTS 5.1.0.2418 and 5.1.0.2444 that caused iSCSI & Fibre Channel to stop responding after trying to open the application.

[Known Issues]
- QTS with newer kernel versions do not support ATTO Fibre Channel adapters. If you have already installed an ATTO Fibre Channel adapter on your device, we do not recommend updating the firmware to QTS 5.1.0 for the time being.

[Other Changes]
Control Panel
- Moved DLNA Media Server settings from Control Panel to Multimedia Streaming Add-on, which can be installed in the App Center.
- The "Network Recycle Bin" feature has been renamed to "Recycle Bin" in Network & File Services.
```

**Comment by sandrolf** [comment]
```
./qts-version --url http://192.168.123.123:8080 --password **********
QTS v5.0.1.2376 Build 20230421 is up to date

./qts-disk-smart --url http://192.168.123.123:8080 --password *********
Checked 7 disks. All are healthy.
* Disk 1 (ST6000VN001-2BB186, SerNo *********, Temp 39°C)
* Disk 2 (ST6000VN001-2BB186, SerNo *********, Temp 36°C)
* Disk 3 (ST4000VN008-2DR166, SerNo *********, Temp 30°C)
* Disk 4 (ST2000DM008-2FR102, SerNo *********, Temp 34°C)
* Disk 5 (ST14000NE0008-2JK101, SerNo *********, Temp 32°C)
* SSD 1 (WDS100T1R0A-68A4W0, SerNo *********, Temp 31°C)
* SSD 3 (SSD 870 QVO 1TB, SerNo S5SVNF0NC27476A, Temp 26°C)|'Disk_1_ST6000VN001-2BB186_*********_temperature'=39;;;0; 'Disk_2_ST6000VN001-2BB186_*********_temperature'=36;;;0; 'Disk_3_ST4000VN008-2DR166_*********_temperature'=30;;;0; 'Disk_4_ST2000DM008-2FR102_*********_temperature'=34;;;0; 'Disk_5_ST14000NE0008-2JK101_*********_temperature'=32;;;0; 'SSD_1_WDS100T1R0A-68A4W0_*********_temperature'=31;;;0; 'SSD_3_SSD_870_QVO_1TB_*********_temperature'=26;;;0;
```

```
./qts-version --url http://192.168.123.123:8080 --password ***********
QTS v5.1.0.2466 Build 20230721 is up to date

./qts-disk-smart --url http://192.168.123.123:8080 --password ***********
Traceback (most recent call last):
  File "/check-plugins/qts-disk-smart/./qts-disk-smart", line 181, in 'module'
    main()
  File "/check-plugins/qts-disk-smart/./qts-disk-smart", line 141, in main
    for disk in data["Disk_Info"]["entry"]:
                ~~~~^^^^^^^^^^^^^
KeyError: 'Disk_Info'
```

**Comment by FildCommander** [comment]
I got the same issue and looked a bit into the source.

I found out that the request has to be a get and not a post.
When I remove the *data=data* from the url.fetch at line 134, it's works.

```python
...
    # get the values
    url = '{}/cgi-bin/disk/qsmart.cgi?func=all_hd_data&sid={}'.format(args.URL, authSid)
    result = lib.base.coe(lib.url.fetch(url, insecure=args.INSECURE, no_proxy=args.NO_PROXY, timeout=args.TIMEOUT))
    data = xmltodict.parse(result)['QDocRoot']
...
```

**Comment by NavidSassan** [comment]
thanks a lot @FildCommander for the testing! please let me know if it works with this fix
