### ISSUE TITLE
disk-usage: FileNotFoundError on Windows Server

### ISSUE THREAD

**Issue by mmartinello** [Linuxfabrik/monitoring-plugins#712]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [X] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

Running the `disk-usage.exe` plugin on two virtual machines running Windows Server 2019 I get this error:

```
PS C:\Program Files\ICINGA2\linuxfabrik> .\disk-usage.exe
Traceback (most recent call last):
  File "C:\PROGRA~1\ICINGA2\LINUXF~1\disk-usage", line 337, in 'module'
  File "C:\PROGRA~1\ICINGA2\LINUXF~1\disk-usage", line 206, in main
  File "C:\PROGRA~1\ICINGA2\LINUXF~1\psutil\__init__.py", line 2005, in disk_usage
  File "C:\PROGRA~1\ICINGA2\LINUXF~1\psutil\_pswindows.py", line 280, in disk_usage
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C'
```

This error is happening on two virtual machines running RDS Terminal Services and does not happen on all other similar virtual machines running the same operating system.

### Steps to reproduce - Plugin call

.\disk-usage.exe

### Environment

Windows Server 2019

### Plugin Version

disk-usage.exe: v2023051201 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by markuslf** [comment]
Installing RDS in Windows:
* Server Manager > "Add roles and features" > "Remote Desktop Services"

**Comment by mmartinello** [comment]
> So I can't reproduce this issue. Anything that I am missing @mmartinello?

These two servers are two full RDS environments installed with this feature:

![Screenshot 2023-09-21 at 15 11 42](https://github.com/Linuxfabrik/monitoring-plugins/assets/3822398/97ade5e6-0032-459e-863f-4798e64143ec)

I really don't know if there is a feature which interferes with your plugin, maybe a special configuration on the RDS environment?

What I can tell you for sure is that these two VMs are completely like the same and they were installed in the same way (but not cloned).

Do you want to have a remote session with me so that we could debug the plugin on that specific machines?

**Comment by Integratinator** [comment]
I have the same issue, but no RDS installed. The plugin was working fine for more than a year. And today stopped working. 
Same error message, however I am using Windows Server 2022 Datacenter (21H2 Build 20348.2031).

Only updated the Microsoft Defender Antivirus yesterday to 1.399.1217.0. Checked for any blocked/removed file actions, but there are none.

**Comment by markuslf** [comment]
I am unable to reproduce this issue.
* Installed Windows Server 2019 Standard.
* Installed our plugins for Windows from download.linuxfabrik.ch, latest release.
* disk-usage.exe is working fine.
* Applied all Windows Updates (and was once again reminded of how nice it is under Linux).
* disk-usage.exe is still working fine.

![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/31855393/5a911e78-87aa-4161-a379-7445bdb9877a)

Any ideas?

**Comment by Integratinator** [comment]
Did another installation of windows updates. No errors now. No idea what caused or solved it, but it seems to be related to windows updates. (I agree about updates under Linux ;-) , but sadly we do not always have the choice.)

**Comment by markuslf** [comment]
Ok, good to know. Thanks for your feedback.

**Comment by Integratinator** [comment]
Not sure how, but after a reboot, the problem is back.

**Comment by markuslf** [comment]
Would be nice to know...
