### ISSUE TITLE
feed: incompatible with Azure status RSS

### ISSUE THREAD

**Issue by tomabg** [Linuxfabrik/monitoring-plugins#756]
### Describe the solution you'd like

RSS Feed for Azure status is not working URL: https://[azure.status.microsoft/de-de/status/feed/](https://azure.status.microsoft/de-de/status/feed/)

Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/feed", line 320, in 'module'
    main()
  File "/usr/lib/nagios/plugins/feed", line 279, in main
    feed_item = lib.base.coe(fetch_feed_latest_item(
  File "/usr/lib/nagios/plugins/feed", line 159, in fetch_feed_latest_item
    success, myfeed = lib.feedparser.parse(
  File "/usr/lib/nagios/plugins/lib/feedparser.py", line 121, in parse
    return (True, parse_rss(soup))
  File "/usr/lib/nagios/plugins/lib/feedparser.py", line 69, in parse_rss
    result['updated'] = soup.rss.channel.pubDate.string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by markuslf** [comment]
Fixed in https://github.com/Linuxfabrik/lib/commit/8688c50ab10f420085a31e2be8199a86924f184b
