### ISSUE TITLE
nextcloud-version - ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by valderaplets** [Linuxfabrik/monitoring-plugins#784]
### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

After upgrading nextcloud version 30, check "nextcloud-version" doesn't work

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/nextcloud-version

### Steps to reproduce - Data

ValueError: No JSON object could be decoded

Traceback (most recent call last):
  File "nextcloud-version.py", line 163, in run_occ
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Environment

- debian 12
- nextcloud 30

### Plugin Version

nextcloud-version: v2024031501 by Linuxfabrik GmbH, Zurich/Switzerland

### Python version

Python 3.11.2

**Comment by valderaplets** [comment]
```
ValueError: No JSON object could be decoded (Traceback for debugging purposes attached)

Traceback (most recent call last):
  File "/srv/git/monitoring-plugins/check-plugins/nextcloud-version/nextcloud-version", line 163, in run_occ
    return json.loads(stdout)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by valderaplets** [comment]
Nevermind, be careful with nextcloud and apc, add `apc.enable_cli ` in your `php.ini `to avoid this error for the good execution of occ command.
